### ISSUE TITLE
missing __init__.py in orangecontrib.recommendation.utils

### ISSUE THREAD

**Issue by noap** [biolab/orange3-recommendation#5]
Hi,

I installed orange3-recommendation per the instructions. When I ran Orange from the terminal, I kept getting this error: 
```
An ImportError occurred while loading entry point 'Recommendation = orangecontrib.recommendation.widgets'
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\Orange\canvas\registry\discovery.py", line 89, in run
    point = entry_point.load()
  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 2355, in load
    return self.resolve()
  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Users\...\AppData\Roaming\Python\Python34\site-packages\orangecontrib\recommendation\__init__.py", line 6, in <module>
    from .base_recommendation import (ModelRecommendation as Model,
  File "C:\Users\...\AppData\Roaming\Python\Python34\site-packages\orangecontrib\recommendation\base_recommendation.py", line 2, in <module>
    from orangecontrib.recommendation.utils import format_data
ImportError: No module named 'orangecontrib.recommendation.utils'
```

After some looking around, I realized that orangecontrib/recommendation/utils didn't have an `__init__.py` file. Since I added it to my cloned orange3-recommendation repo, I have been able to see the Recommendation section in the toolbox bar. I figured this might help others as well.

Thanks!

**Comment by salvacarrion** [comment]
Thanks! It's already solved.
